// @generated by protoc-gen-es v1.7.2
// @generated from file v1/hello_world.proto (package grpc.greeter.helloworld, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// 一般情况package可以按照「服务类型.项目名.服务名」方式命名

import { proto3 } from "@bufbuild/protobuf";

/**
 * 定义请求的message
 *
 * @generated from message grpc.greeter.helloworld.HelloRequest
 */
export const HelloRequest = proto3.makeMessageType(
  "grpc.greeter.helloworld.HelloRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * 定义响应的message
 *
 * @generated from message grpc.greeter.helloworld.HelloReply
 */
export const HelloReply = proto3.makeMessageType(
  "grpc.greeter.helloworld.HelloReply",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

