// @generated by protoc-gen-es v1.7.2
// @generated from file v1/hello_world.proto (package grpc.greeter.helloworld, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// 一般情况package可以按照「服务类型.项目名.服务名」方式命名

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * 定义请求的message
 *
 * @generated from message grpc.greeter.helloworld.HelloRequest
 */
export declare class HelloRequest extends Message<HelloRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<HelloRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grpc.greeter.helloworld.HelloRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloRequest;

  static equals(a: HelloRequest | PlainMessage<HelloRequest> | undefined, b: HelloRequest | PlainMessage<HelloRequest> | undefined): boolean;
}

/**
 * 定义响应的message
 *
 * @generated from message grpc.greeter.helloworld.HelloReply
 */
export declare class HelloReply extends Message<HelloReply> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  constructor(data?: PartialMessage<HelloReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grpc.greeter.helloworld.HelloReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HelloReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HelloReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HelloReply;

  static equals(a: HelloReply | PlainMessage<HelloReply> | undefined, b: HelloReply | PlainMessage<HelloReply> | undefined): boolean;
}

